[package]
name = "tlib_core"
version = "0.1.0"
authors = ["tajoy <tj328111241@gmail.com>"]

[lib]
name = "tlib_core"
path = "src/lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
rustc-serialize = "^0.3.22"